### ISSUE TITLE
Make test to check that mission2 was completed

### ISSUE THREAD

**Issue by Christdej** [equinor/isar-turtlebot#38]
Check that the robot was able to get to the finish postion in the mission and that there are images uploaded. 
This repo can be used as a starting point:
https://github.com/equinor/eq_robot_ci_simulation/blob/main/ros_noetic/eq_robot_ci_simulation/scripts/monitor_mission.py

**Comment by aestene** [comment]
In the given example the test has passed based on how much time has passed without the ros server shutting down (I think). Would it just be simpler to run mission 2 with ISAR and check that the correct amount of inspections have been uploaded and that their metadata for pose is within the expected fault tolerance? 

There are many things we could do to check tests, but this seems like a much easier way of checking.
