### ISSUE TITLE
Move image functionality out of rosbridge imagetopic

### ISSUE THREAD

**Issue by knord94** [equinor/isar-turtlebot#50]
Functionality for providing is currently inside `ImageTopic`. This topic is listened to permanently, then the image data is stored during an inspection. 

Suggested solution: Subscribe to the image topic only during inspection task and unsubscribe. Additionally create a new module handling the image data retrieved from the topic. Alternatively this can be placed in an existing module.

**Comment by Christdej** [comment]
#40
